services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/jovyan/workspaces
      - ~/downloads/ytdlp:/home/jovyan/downloads/ytdlp
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8888:8888"
    depends_on:
      - pgvector
    env_file:
      - .env
    # GPU support enabled
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  pgvector:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jupyter-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password  # Move to .env for production
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Optional heavy GPU service for vllm builds. Disabled by default; enable with
  # `docker compose --profile vllm up --build vllm` when you want to build/run vllm.
  vllm:
    profiles: ["vllm"]
    build:
      context: .
      dockerfile: Dockerfile.vllm
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  postgres_data: {}
