services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/jovyan/workspaces
      - ~/downloads/ytdlp:/home/jovyan/downloads/ytdlp
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8888:8888"
    depends_on:
      - pgvector
    env_file:
      - .env
    # If GPU needed, uncomment:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

  pgvector:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jupyter-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password  # Move to .env for production
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}